services:
  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data

  ride-service:
    build: ./ride_service_module
    environment:
      MONGO_URL: mongodb://admin:admin123@mongo:27017/?authSource=admin
      MONGO_DB: ride_db
      REDIS_URL: redis://redis:6379
      PORT: 3005
    ports:
      - "3005:3005"
    depends_on:
      - mongo
      - redis

volumes:
  mongodata:
  redisdata:
